-- notifications was declared PARTITION BY RANGE (created_at) in the original Phase 1 schema (V6) but has
-- zero partitions — the same bug already found and fixed for reports/moderation_actions in V11 (confirmed
-- live before writing this: `SELECT count(*) FROM pg_inherits WHERE inhparent = 'notifications'::regclass`
-- returned 0). This phase is the first code to ever write to it. Same rolling-24-month-window fix, same
-- reasoning: a real deployment still needs an automated job to keep extending this — flagged, not built,
-- same as V11. notifications_unread_idx (declared in V6, before any partitions existed) automatically
-- propagates to each partition created below — Postgres treats a non-ONLY CREATE INDEX on a partitioned
-- parent as a template for partitions created later, the same mechanism V12 relied on.
DO $$
DECLARE
  month_start date := date_trunc('month', now());
  month_end date;
  i int;
BEGIN
  FOR i IN 0..23 LOOP
    month_end := month_start + INTERVAL '1 month';
    EXECUTE format('CREATE TABLE IF NOT EXISTS notifications_%s PARTITION OF notifications FOR VALUES FROM (%L) TO (%L)',
                    to_char(month_start, 'YYYY_MM'), month_start, month_end);
    month_start := month_end;
  END LOOP;
END $$;

-- Media processing pipeline. media_processing_status_check's autogenerated name confirmed live via
-- `\d media` before writing this (matches the V7 inline CHECK's default <table>_<column>_check naming).
ALTER TABLE media ADD COLUMN media_type TEXT NOT NULL DEFAULT 'image' CHECK (media_type IN ('image','video'));
ALTER TABLE media ALTER COLUMN media_type DROP DEFAULT;  -- default was only to backfill; every future insert sets it explicitly
ALTER TABLE media ADD COLUMN thumbnail_key TEXT;
ALTER TABLE media ADD COLUMN display_key TEXT;
ALTER TABLE media ADD COLUMN width INTEGER;
ALTER TABLE media ADD COLUMN height INTEGER;
ALTER TABLE media ADD COLUMN duration_seconds NUMERIC;
ALTER TABLE media ADD COLUMN attempt_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE media ADD COLUMN error_message TEXT;

ALTER TABLE media DROP CONSTRAINT media_processing_status_check;
ALTER TABLE media ADD CONSTRAINT media_processing_status_check
    CHECK (processing_status IN ('pending','uploaded','processing','ready','failed'));

-- Matches each worker's claim query exactly (ORDER BY created_at, WHERE processing_status = 'uploaded').
CREATE INDEX media_pending_idx ON media (created_at) WHERE processing_status = 'uploaded';

ALTER TABLE posts ADD COLUMN media_id UUID REFERENCES media(id);
