ALTER TABLE posts ADD COLUMN edited_at TIMESTAMPTZ;
ALTER TABLE posts ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE comments ADD COLUMN edited_at TIMESTAMPTZ;
ALTER TABLE comments ADD COLUMN deleted BOOLEAN NOT NULL DEFAULT false;
